AWSTemplateFormatVersion: 2010-09-09
Description: Template for CodeCommit and ECR Repositories

Parameters:

  CreateSourceRepository:
    Description: Should a CodeCommit repository be created (false for GitHub/Bitbucket)?
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  SourceRepositoryName:
    Description: Name used for the CodeCommit/GitHub/Bitbucket repository
    MinLength: 1
    MaxLength: 100
    AllowedPattern: ^[\w/\.-]+
    Type: String

  SourceRepositoryDescription:
    Description: Description for the CodeCommit repository
    MinLength: 0
    MaxLength: 1000
    Type: String

  ImageRepositoryName:
    Description: Name used for the ECR repository
    MinLength: 2
    MaxLength: 256
    AllowedPattern: ^(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
    Type: String

  LifecyclePolicy:
    Description: "See also: https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html"
    Type: String
    MinLength: 100
    MaxLength: 30720
    Default: "{\"rules\":[{\"rulePriority\":1,\"description\":\"Remove untagged after 2w\",\"selection\":{\"tagStatus\":\"untagged\",\"countType\":\"sinceImagePushed\",\"countUnit\":\"days\",\"countNumber\":14},\"action\":{\"type\":\"expire\"}}]}"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Source Repository Settings"
        Parameters:
          - CreateSourceRepository
          - SourceRepositoryName
          - SourceRepositoryDescription
      - Label:
          default: "Registry Settings"
        Parameters:
          - ImageRepositoryName
          - LifecyclePolicy
    ParameterLabels:
      CreateSourceRepository:
        default: "Create Source Repository?"
      SourceRepositoryName:
        default: "Source Repository Name"
      SourceRepositoryDescription:
        default: "Source Repository Description"
      ImageRepositoryName:
        default: "Image Repository Name"
      LifecyclePolicy:
        default: "Lifecycle Policy"

Conditions:
  CreateSourceRepository: !Equals ["true", !Ref CreateSourceRepository]

Resources:
  SourceRepository:
    Type: AWS::CodeCommit::Repository
    Condition: CreateSourceRepository
    Properties:
      RepositoryDescription: !Ref SourceRepositoryDescription
      RepositoryName: !Ref SourceRepositoryName

  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: AES256
      RepositoryName: !Ref ImageRepositoryName
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicy

Outputs:
  SourceRepository:
    Description: Name used for the CodeCommit/GitHub/Bitbucket repository
    Value: !Ref SourceRepositoryName
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "SourceRepositoryName"]]

  ImageRepository:
    Description: Name used for the ECR repository
    Value: !Ref ImageRepositoryName
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", "ImageRepositoryName"]]