AWSTemplateFormatVersion: 2010-09-09
Description: Template for Multi-Arch Operator SDK Builds (AARCH64, AMD64) based on CodeCommit & CodePipeline w/Source Trigger

Parameters:
  BuildStackName:
    Description: Name of the stack containing build projects, roles & pipeline bucket
    Type: String
    Default: aws-codebuild-podman
  RepositoryStackName:
    Description: Name of the stack containing source and image repositories
    Type: String
    Default: aws-codebuild-podman-repositories
  PipelineFrequency:
    Description: Scheduled invocation of the pipeline
    Type: String
    Default: none
    AllowedValues:
      - "none"
      - "1 hour"
      - "4 hours"
      - "12 hours"
      - "1 days"
      - "7 days"
      - "14 days"
      - "28 days"
  PipelineSourceTrigger:
    Description: Should this pipeline trigger on source changes?
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  Branch:
    Description: "Name of the CodeCommit repository branch. (See also: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-source-version.html)"
    Type: String
    Default: main
  TargetTag:
    Description: The base tag name for the manifest and derivative architecture builds.
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Related Stacks"
        Parameters:
          - BuildStackName
          - RepositoryStackName
      - Label:
          default: "Pipeline Information"
        Parameters:
          - PipelineFrequency
          - PipelineSourceTrigger
          - PipelineTriggerImageChange
      - Label:
          default: "Source Repository Information"
        Parameters:
          - Branch
      - Label:
          default: "Container Repository Information"
        Parameters:
          - TargetTag
    ParameterLabels:
      BuildStackName:
        default: "Build Stack Name"
      RepositoryStackName:
        default: "Repository Stack Name"
      PipelineFrequency:
        default: "Pipeline Frequency"
      PipelineSourceTrigger:
        default: "Pipeline Source Trigger"
      PipelineTriggerImageChange:
        default: "Pipeline ECR Image Trigger"
      TargetTag:
        default: "Target Tag"

Conditions:
  HasRate: !Not [!Equals ["none", !Ref PipelineFrequency]]
  EnableSourceTrigger: !Equals ["true", !Ref PipelineSourceTrigger]

Resources:

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !ImportValue
          'Fn::Sub': '${BuildStackName}-PipelineBucket'
        Type: S3
      Name: !Ref "AWS::StackName"
      RoleArn: !ImportValue
        'Fn::Sub': '${BuildStackName}-ContainerPipelineRoleArn'
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                BranchName: !Ref Branch
                PollForSourceChanges: false
                RepositoryName: !ImportValue
                  'Fn::Sub': '${RepositoryStackName}-SourceRepositoryName'
              Region: !Ref "AWS::Region"
              OutputArtifacts:
                - Name: SourceArtifact
              Namespace: SourceVariables
        - Name: Build-Operators
          Actions:
            - Name: Build-AMD
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !ImportValue
                  'Fn::Sub': '${BuildStackName}-OperatorAmd64Build'
                EnvironmentVariables: !Join ["", ["[",
                    "{\"name\":\"IMAGE_TAG\",\"value\":\"", !Ref TargetTag, "\",\"type\":\"PLAINTEXT\"},",
                    "{\"name\":\"IMAGE_REPO_NAME\",\"value\":\"", Fn::ImportValue: !Sub "${RepositoryStackName}-ImageRepositoryName", "\",\"type\":\"PLAINTEXT\"}",
                    "]"
                ]]
              Region: !Ref "AWS::Region"
              InputArtifacts:
                - Name: SourceArtifact
            - Name: Build-ARM
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !ImportValue
                  'Fn::Sub': '${BuildStackName}-OperatorAarch64Build'
                EnvironmentVariables: !Join ["", ["[",
                    "{\"name\":\"IMAGE_TAG\",\"value\":\"", !Ref TargetTag, "\",\"type\":\"PLAINTEXT\"},",
                    "{\"name\":\"IMAGE_REPO_NAME\",\"value\":\"", Fn::ImportValue: !Sub "${RepositoryStackName}-ImageRepositoryName", "\",\"type\":\"PLAINTEXT\"}",
                    "]"
                ]]
              Region: !Ref "AWS::Region"
              InputArtifacts:
                - Name: SourceArtifact
        - Name: Build-Manifests
          Actions:
            - Name: Build-Manifests
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName:  !ImportValue
                  'Fn::Sub': '${BuildStackName}-ManifestBuild'
                EnvironmentVariables: !Join ["", ["[",
                                                  "{\"name\":\"IMAGE_TAG\",\"value\":\"", !Ref TargetTag, "\",\"type\":\"PLAINTEXT\"},",
                                                  "{\"name\":\"IMAGE_REPO_NAME\",\"value\":\"", Fn::ImportValue: !Sub "${RepositoryStackName}-ImageRepositoryName", "\",\"type\":\"PLAINTEXT\"}",
                                                  "]"
                ]]
              Region: !Ref "AWS::Region"
              InputArtifacts:
                - Name: SourceArtifact

  PipelineSourceRule:
    Type: AWS::Events::Rule
    Condition: EnableSourceTrigger
    Properties:
      Description: "Trigger container pipeline on source changes"
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Join [":", ["arn:aws:codecommit", !Ref "AWS::Region", !Ref "AWS::AccountId", Fn::ImportValue: !Sub "${RepositoryStackName}-SourceRepositoryName" ]]
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref Branch
      Targets:
        - Arn: !Join [":", ["arn:aws:codepipeline", !Ref "AWS::Region", !Ref "AWS::AccountId", !Ref Pipeline]]
          RoleArn: !ImportValue
            'Fn::Sub': '${BuildStackName}-PipelineTriggerRoleArn'
          Id: !Join ["-", ["codepipeline", !Ref "AWS::StackName"]]

  PipelineTimedRule:
    Type: AWS::Events::Rule
    Condition: HasRate
    Properties:
      Description: !Join [" ", ["Run every", !Ref PipelineFrequency]]
      ScheduleExpression: !Join ["", ["rate(", !Ref PipelineFrequency, ")"]]
      Targets:
        - Arn: !Join [":", ["arn:aws:codepipeline", !Ref "AWS::Region", !Ref "AWS::AccountId", !Ref Pipeline]]
          RoleArn: !ImportValue
            'Fn::Sub': '${BuildStackName}-PipelineTriggerRoleArn'
          Id: !Join ["-", ["codepipeline", !Ref "AWS::StackName"]]
